#   TESTER

server {
    listen       8080;
    server_name  localhost;
    root    ./YoupiBanane/;
    client_max_body_size 100;

    location / {
        allow_methods GET;
        cgi .bla ./cgi_tester;
    }

    location /post_body {
        allow_methods POST;
        upload_store ./YoupiBanane/;
        
    }

    location /directory {
        root   ./YoupiBanane/;
        allow_methods GET;
        index  youpi.bad_extension;
        
    }
}
