#  ||   Configuration File Template  ||

server {
    listen 8080; # alternative - 127.0.0.1:8080
    server_name localhost;
    client_max_body_size 10000;
    
    # Global root for all locations
    root ./www/example; 

    # Custom Error Pages
    error_page 404 /errors/404.html;
    error_page 500 502 503 504 /errors/50x.html;

    # 1. Standard Folder (With internal CGI support)
    location / {
        allow_methods GET POST;
        index index.html;
        upload_store ./www/uploads;
        cgi .py /usr/bin/python3;
    }

    # 2. Dedicated CGI Endpoint (Extension matching)
    location *.php {
        allow_methods GET POST;
        cgi_pass /usr/bin/php-cgi;
        upload_store ./www/uploads;
    }

    # 3. HTTP Redirect
    location /old-site {
        allow_methods GET;
        return 301 http://127.0.0.1:8080/new-site;
    }

    # 4. Directory Listing
    location /directory-listing {
        autoindex on;
        allow_methods GET;
    }
}

#  ||   Configuration Guide  ||

#    Server {
#        listen <IP:PORT | PORT>;
#        server_name <SERVER NAME>;
#        client_max_body_size <xxx | xxxM>; 
#        root <DIRECTORY>;
#        error_page <STATUS CODE> <PATH>;
#        error_page <STATUS CODE> <STATUS CODE> <STATUS CODE> <PATH>;

#        # 1. Standard Folder (With internal CGI support)
#        location <URI> {
#            allow_methods <GET | POST | PUT | DELETE | HEAD | PATCH>;
#            index <INDEX>;
#            upload_store <DIRECTORY>;
#            cgi <EXTENSION> <EXECUTABLE PATH>;
#        }

#        # 2. Dedicated CGI Endpoint (Extension matching)
#        location *<EXTENSION> {
#            allow_methods <GET | POST | PUT | DELETE | HEAD | PATCH>;
#            cgi_pass <EXECUTABLE PATH>;
#            upload_store <DIRECTORY>; (if POST allowed)
#        }

#        # 3. HTTP Redirect
#        location <URI> {
#            allow_methods <GET | POST | PUT | DELETE | HEAD | PATCH>;
#            return <STATUS CODE> <URL>;
#        }
#
#        # 4. Directory Listing
#        location /directory-listing {
#            allow_methods <GET | POST | PUT | DELETE | HEAD | PATCH>;
#            autoindex <on | off>;
#        }
#   }
