#   WEBSERVER CONFIGURATION

    server {
        listen       8080;
        server_name  localhost;
        root    ./www;
        client_max_body_size 10M;

        location / {
            root   ./src;
            index  file.something;
            allow_methods GET PATCH DELETE PUT;
            # return 300 /;
            cgi .py ./webserv;
            upload_store ./src;
        }

        location /uploads {
            root   ./src;
            autoindex on;
            allow_methods GET PATCH DELETE PUT;
        }

        error_page   500 502 503 504  /50x.html;
    }
