#   WEBSERVER CONFIGURATION

    server {
        listen       8080;
        server_name  localhost;
        root    ./www;
        client_max_body_size 10M;

        location / {
            root   ./www/;
            index  index.html hello.html;
            allow_methods GET POST PATCH DELETE PUT;
            # return 300 /home;
            cgi .py /usr/bin/python3;
            upload_store ./www/uploads;
        }

        # location /home {
        #     root   ./src;
        #     index  index.html;
        #     allow_methods GET POST PATCH DELETE PUT;
        #     # return 302 /home;
        #     cgi .py ./webserv;z
        #     upload_store ./src;
        # }

        location /uploads {
            root   ./www/;
            autoindex on;
            allow_methods GET PATCH DELETE PUT;
        }

        location /redir {
            return 301 http://youtube.com; # works!! nice
            allow_methods GET PATCH DELETE PUT;
        }

        location *.bla {
            allow_methods POSt;
            cgi_pass /usr/bin/python3;
        }

        error_page   500 502 503 504  /50x.html;
    }
