server {
    listen       8080;
    server_name  site-a.com;

    location / {
        root   html;
        index  index.html;
    }
}

server {
    listen       9090;
    server_name  site-b.com;

    location / {
        root   html;
        index  index.html;
    }
}