#   WEBSERVER CONFIGURATION

	server {
		listen	   8080;
		server_name  localhost;
		root	./www;
		client_max_body_size 5M;

		location / {
			root   ./www/;
			index  index.html goodbye.html hello.html;
			allow_methods GET;
		}

		location /home {
			root   ./www/home;
			index  home.html;
			allow_methods GET;
		}


		# !! "view" pages
		location /board {
			root   ./www/board;
			index  index.html;
			allow_methods GET;
		}

		location /gallery {
			root   ./www/gallery;
			index  index.html;
			allow_methods GET;
		}

		location /video {
			root   ./www/video;
			index  index.html;
			allow_methods GET;
		}


		# !! "create" pages
		location /write {
			root   ./www/write;
			index  index.html;
			allow_methods GET POST;
			upload_store ./www/uploads;
		}

		location /picture {
			root   ./www/picture;
			index  index.html;
			allow_methods GET POST;
			upload_store ./www/uploads;
		}

		location /file {
			root   ./www/file;
			index  index.html;
			allow_methods GET POST;
			upload_store ./www/uploads;
		}


		# !! "tests" pages
		location /cgi {
			root   ./www/cgi;
			index  index.html;
			allow_methods GET;
		}

		location /redir {
			root   ./www/redir;
			index  index.html;
			allow_methods GET;
		}

		location /autoidx {
			root   ./www/listing;
			index  index.html;
			allow_methods GET;
		}


		# !! redirections
		location /yt {
			return 301 https://youtube.com;
			allow_methods GET;
		}

		location /fun {
			return 301 https://theuselessweb.com/;
			allow_methods GET;
		}

		location /community {
			return 308 /board;
			allow_methods GET;
		}


		# !! directory listing
		location /uploads {
			root   ./www/uploads;
			autoindex on;
			allow_methods GET;
		}

		location /assets {
			root   ./www/assets;
			autoindex on;
			allow_methods GET;
		}

		location /all {
			autoindex on;
			allow_methods GET;
		}

		location /home/sublisting {
			root   ./www/home/subfolder;
			autoindex on;
			allow_methods GET;
		}

		# !! cgi extention location
		location *.py {
			root	./www/cgi_folder;
			allow_methods GET POST;
			cgi_pass /usr/bin/python3;
			upload_store ./www/uploads;
		}

		error_page   500 502 503 504  /50x.html;
	}
